preprocess:
  impute: True
  resample: True  
  filter_years: False
  imputation_method: seasonal
  resample_method: mean
  sampling_rate: '1h'
  filter_range: 
    - 2014
    - 2016
  fix_data_errors: True
  encode_sinusoidal: True
  cyclic_cols:  
    - "wd"
  anomaly_cols: 
    - "wv"
    - "max__wv"

feature_engineering:
  window_size: 5
  train_test_split: 0.75
  test_eval_split: 0.50
  scaler: standard_scaler
  period: '1d'
  drop_features: 
    - 'wd_deg'
    - 'wv_ms'
    - 'max_wv_ms'

train:
  model_type: LSTM
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
